version: '3'

services:
  consul:
    container_name: consul
    #image: consul:1.4.0
    #image: progrium/consul:latest
    image: gliderlabs/consul-server:latest
    ports:
      - 8500:8500
      - 8300:8300
    #command: "-server -ui-dir /ui -bootstrap-expect 1 -client=0.0.0.0 -advertise=127.0.0.1"
    command: "-server -ui -bootstrap-expect 1 -data-dir=/consul/data -client=0.0.0.0 -advertise=127.0.0.1"
    # -bind=92.168.56.101 -ui  -bootstrap-expect=1 -advertise=192.168.56.101
    #-data-dir /consul/data 
    #command: consul agent -server -advertise=192.168.56.101 -data-dir=/consul/data -ui
    #-bootstrap-expect=1 -bind=127.0.0.1 -ui -data-dir /consul/data -config-dir /consul/config
    #command: consul agent -server -data-dir /consul/data -ui-dir /ui -bootstrap-expect 1 -client=0.0.0.0 -advertise=127.0.0.1
    #-bind=172.16.231.11  -bootstrap-expect=2 -retry-join=172.16.231.12 -retry-join=172.16.231.13
    volumes:
      - /var/lib/consul/data:/consul/data
    #volumes:
    #  - ./consul-config/config.json:/consul/config/config.json
