version: '2'

services:
  consul:
    container_name: consul
    image: consul:1.5.0
    networks:
      micronet: 
        ipv4_address: 172.16.238.3
    ports:
      - 8500:8500
      - 8300:8300
    command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0"
    volumes:
      - ./consul-config:/consul/config
      - /var/lib/consul/data:/consul/data
