version: '3'
services:
  consul:
    container_name: consul
    image: consul:1.4.0
    ports:
      - 8500:8500
    #volumes:
    #  - ./consul-config/config.json:/consul/config/config.json
    #command: agent -server -bootstrap-expect=1 -ui -bind=127.0.0.1
