version: '2'

services:
  db:
    container_name: db
    image: postgres:11.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=micro
    networks:
      micronet: 
        ipv4_address: 172.16.238.2
    ports:
      - "5492:5432"
    volumes:
      - ../db/init-sql:/docker-entrypoint-initdb.d
      - /var/lib/postgres-micro/data:/var/lib/postgresql/data
#    volumes:
#      - database_data:/var/lib/postgresql/data
