version: '3'

services:
  db:
    container_name: db
    image: postgres:11.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=micro
    ports:
      - "5492:5432"
#    volumes:
#      - database_data:/var/lib/postgresql/data
