version: '3.7'

services:
  db-keycloak:
    container_name: db-keycloak
    image: postgres:11.1
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    ports:
      - "5482:5432"
    volumes:
      - /var/lib/postgres-keycloak/data:/var/lib/postgresql/data
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:4.5.0.Final
    volumes:
      #- /home/user/work/jproj/java-micro/docker/services/keycloak/config/micro-realm-export.json:/etc/settings/micro-realm-export.json
      - ../keycloak/config:/etc/settings
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /etc/settings/micro-realm-full.json
      #KEYCLOAK_IMPORT: /etc/settings/micro-users.json
    ports:
      - 8180:8080
    depends_on:
      - db-keycloak