version: '3.7'

services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak:6.0.1
    volumes:
      #- /home/user/work/jproj/java-micro/docker/services/keycloak/config/micro-realm-export.json:/etc/settings/micro-realm-export.json
      - ../keycloak/config:/etc/settings
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db #db-keycloak
      DB_DATABASE: micro #keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /etc/settings/micro-realm-full.json
      #KEYCLOAK_IMPORT: /etc/settings/micro-users.json
    ports:
      - 8180:8080
    depends_on:
      - db