version: '2'

networks:
    micronet:
        # use the bridge driver, but enable IPv6
        driver: bridge
#        driver_opts:
 #           com.docker.network.enable_ipv6: "true"
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
                  gateway: 172.16.238.1
